ubuntu@ip-172-31-90-132:~/microservice-kube_udacity_lab$ ./run_kubernetes.sh 
error: failed to create deployment: deployments.apps "py-helloworld-kube" already exists
NAME                                 READY   STATUS    RESTARTS   AGE
py-helloworld-kube-7c657fc4b-zdl97   1/1     Running   0          51s
Forwarding from 0.0.0.0:8000 -> 80
Handling connection for 8000
[2023-07-13 12:40:51,697] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2023-07-13 12:40:51,700] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-07-13 12:40:51,723] INFO in app: Scaling Payload: 
{payload}
[2023-07-13 12:40:51,727] INFO in app: Output Prediction: 
[20.35373177134412]
127.0.0.1 - - [13/Jul/2023 12:40:51] "POST /predict HTTP/1.1" 200 -
